GET /status HTTP/1.1
Host: localhost:8080

###

POST /feed HTTP/1.1
Host: localhost:8080

###

POST /pet HTTP/1.1
Host: localhost:8080

###

POST /meow HTTP/1.1
Host: localhost:8080

###
POST /water HTTP/1.1
Host: localhost:8080